apiVersion: apps/v1
kind: Deployment
metadata:
  name: azagent
  namespace: azagent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azagent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: azagent
    spec:
      containers:
      - env:
        - name: AGENT_ALLOW_RUNASROOT
          value: "true"
        envFrom:
        - secretRef:
            name: azdevops
        image: hasanalperen/azuredevopsagent:v1.0
        imagePullPolicy: IfNotPresent
        name: azagent-container
        securityContext:
          privileged: true
          runAsUser: 0
